#Configurations for registry factory
host: "" #Listen host
port: 7878 #Listen port
dockerd: #Docker runtime
  host: "10.160.185.248"
  port: 2375
  admin: "admin"
  password: "Harbor12345"
harbor: #Harbor
  host: "10.160.178.186"
  protocol: http
npm_registry: #npm
  namespace: "npm-registry"
  base_image: "stevenzou/npm-registry"
  base_image_tag: "latest"  
pip_registry: #pip
  namespace: "registry-factory"
  base_image: ""
  base_image_tag: ""
